# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/awme/stocket/models/expense/columns.yaml

# Model Class name
modelClass: AWME\Stocket\Models\Expense

# List Title
title: awme.stocket::lang.expenses.manage_expenses

# Link URL for each record
recordUrl: awme/stocket/expenses/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
