# ===================================
#  List Behavior Config
# ===================================

categories:
    label: awme.stocket::lang.categories.category
    view:
        list: $/awme/stocket/models/category/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        showSearch: true
        recordsPerPage: 10
        list: $/awme/stocket/models/category/columns.yaml
        form: $/awme/stocket/models/category/fields.yaml
