# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: awme.stocket::lang.products.product

# Model Form Field configuration
form: $/awme/stocket/models/product/fields.yaml

# Model Class name
modelClass: AWME\Stocket\Models\Product

# Default redirect location
defaultRedirect: awme/stocket/products

# Create page
create:
    title: awme.stocket::lang.products.new_product
    redirect: awme/stocket/products/update/:id
    redirectClose: awme/stocket/products

# Update page
update:
    title: awme.stocket::lang.products.edit_product
    redirect: awme/stocket/products
    redirectClose: awme/stocket/products

# Preview page
preview:
    title: awme.stocket::lang.products.preview_product
