# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: awme.stocket::lang.tills.operation

# Model Form Field configuration
form: $/awme/stocket/models/till/fields.yaml

# Model Class name
modelClass: AWME\Stocket\Models\Till

# Default redirect location
defaultRedirect: awme/stocket/tills

# Create page
create:
    title: awme.stocket::lang.tills.new_operation
    redirect: awme/stocket/tills/update/:id
    redirectClose: awme/stocket/tills

# Update page
update:
    title: awme.stocket::lang.tills.edit_operation
    redirect: awme/stocket/tills
    redirectClose: awme/stocket/tills

# Preview page
preview:
    title: awme.stocket::lang.tills.preview_operation