# ===================================
#  List Behavior Config
# ===================================

products:
    label: Product
    view:
        list: $/awme/stocket/models/product/sale_columns.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        recordsPerPage: 25
        list: $/awme/stocket/models/product/sale_columns.yaml
        #form: $/awme/stocket/models/product/sale_fields.yaml
