# ===================================
#  List Behavior Config
# ===================================

products:
    label: awme.stocket::lang.sales.product
    view:
        list: $/awme/stocket/models/product/sale_columns.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        recordsPerPage: 10
        list: $/awme/stocket/models/product/sale_columns.yaml
        #form: $/awme/stocket/models/product/sale_fields.yaml
