# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: awme.stocket::lang.sales.sale

# Model Form Field configuration
form: $/awme/stocket/models/sale/fields.yaml

# Model Class name
modelClass: AWME\Stocket\Models\Sale

# Default redirect location
defaultRedirect: awme/stocket/sales

# Create page
create:
    title: awme.stocket::lang.sales.new_sale
    form: $/awme/stocket/models/sale/create_fields.yaml
    redirect: awme/stocket/sales/update/:id
    redirectClose: awme/stocket/sales

# Update page
update:
    title: awme.stocket::lang.sales.edit_sale
    form: $/awme/stocket/models/sale/update_fields.yaml
    redirect: awme/stocket/sales
    redirectClose: awme/stocket/sales

# Preview page
preview:
    title: awme.stocket::lang.sales.preview_sale